# Namespace for all ci/cd resources (jenkins, build slaves, ...)
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
# Namespace for staging stage - all performance tested builds will be pushed to staging
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# Namespace for production stage - at a specific point in time, the artefacts in staging will be
# marked for production and then deployed to the production namespace
apiVersion: v1
kind: Namespace
metadata:
  name: production